version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:

    networks:
      - clarusnet
  
  myapp:
    image: muslumhanozturk/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    
    networks:
      - clarusnet

networks:
  clarusnet:
